language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

env: 
  global:
    - MEMCACHE_HOST=localhost
    - REDIS_URIS=redis://localhost:63791,redis://localhost:63792,redis://localhost:63793
    - MYSQL_DSN="mysql:host=localhost;dbname=test"
    - MYSQL_USER=travis
    - PGSQL_DSN="pgsql:host=localhost;dbname=test;"
    - PGSQL_USER=postgres

services:
  - memcached
  - mysql
  - postgresql
  - redis-server

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libzstd-dev=1.3.1
  - pecl update-channels
  - yes | pecl install -f igbinary lzf redis
  - phpenv config-add tests/php-travis.ini
  - redis-server --port 63791 &
  - redis-server --port 63792 &
  - redis-server --port 63793 &

install:
  - composer install --no-progress --no-scripts --no-suggest --no-interaction

before_script:
  - mysql -e 'create database test;'
  - psql  -c 'create database test;' -U postgres

script:
  - vendor/bin/phpunit 
  - vendor/bin/phpcs --standard=PSR2 classes/ tests/

